version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-loader"
      eslint:
        patterns:
          - "eslint"
          - "eslint-config-*"
          - "eslint-plugin-*"
          - "typescript-eslint"
      lingui:
        patterns:
          - "@lingui/*"
      patternfly:
        patterns:
          - "@patternfly/*"
      react:
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
