name: Automerge

on:
  pull_request_target:
    branches: [ 'main' ]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout pulp-ui (${{ github.ref }})"
      uses: actions/checkout@v4

    - name: "Install node 20"
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: "Automerge the PR"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr merge "${{ github.event.pull_request.number }}" -s --auto
